sonata_admin:
    title: 'Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        form_type: horizontal
    templates:
        layout: layout.html.twig

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

